apiVersion: v1
     kind: Service
     metadata:
       name: config
       namespace: {{ .Release.Namespace }}
     spec:
       selector:
         app: config
       ports:
       - protocol: TCP
         port: {{ .Values.config.port }}
         targetPort: {{ .Values.config.port }}
         nodePort: {{ add .Values.config.port 20000 }}
       type: NodePort