apiVersion: v1
     kind: Service
     metadata:
       name: customers
       namespace: {{ .Release.Namespace }}
     spec:
       selector:
         app: customers
       ports:
       - protocol: TCP
         port: {{ .Values.customers.port }}
         targetPort: {{ .Values.customers.port }}
         nodePort: {{ add .Values.customers.port 20000 }}
       type: NodePort