apiVersion: v1
     kind: Service
     metadata:
       name: vets
       namespace: {{ .Release.Namespace }}
     spec:
       selector:
         app: vets
       ports:
       - protocol: TCP
         port: {{ .Values.vets.port }}
         targetPort: {{ .Values.vets.port }}
         nodePort: {{ add .Values.vets.port 20000 }}
       type: NodePort