version: '2'

services:
  config-server:
    image: spring-petclinic-config-server:1.0
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: spring-petclinic-discovery-server:1.0
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    ports:
     - 8761:8761

  customers-service:
    image: spring-petclinic-customers-service:1.0
    container_name: customers-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    ports:
    - 8081:8081

  visits-service:
    image: spring-petclinic-visits-service:1.0
    container_name: visits-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    ports:
     - 8082:8082

  vets-service:
    image: spring-petclinic-vets-service:1.0
    container_name: vets-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    ports:
     - 8083:8083

  api-gateway:
    image: spring-petclinic-api-gateway:1.0
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    ports:
     - 8080:8080

#  tracing-server:
#    image: openzipkin/zipkin
#    container_name: tracing-server
#    mem_limit: 512M
#    environment:
#    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
#    ports:
#     - 9411:9411

  admin-server:
    image: spring-petclinic-admin-server:1.0
    container_name: admin-server
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    ports:
     - 9090:9090
#
#  ## Grafana / Prometheus
#
#  grafana-server:
#    build: ./docker/grafana
#    container_name: grafana-server
#    mem_limit: 256M
#    ports:
#    - 3000:3000
#
#  prometheus-server:
#    build: ./docker/prometheus
#    container_name: prometheus-server
#    mem_limit: 256M
#    ports:
#    - 9091:9090
