# /chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . }}
  labels:
    app: {{ include "petclinic.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "petclinic.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

