spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

---
spring:
  config:
    activate:
      on-profile: vm
    import: configserver:http://141.22.10.81:8888
