# helm-charts/petclinic-umbrella/charts/customers-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "customers-service.fullname" . }}
  labels:
    {{- include "customers-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} # Target customers-service port
      protocol: TCP
      name: http
  selector:
    {{- include "customers-service.selectorLabels" . | nindent 4 }}