# This workflow will build a Java project with Maven, and deploy on ASA using blue/green release support
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CD, Build & deploy for 1 module

on:
  workflow_dispatch:

env:
  
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  
  AZURE_RESOURCE_GROUP_NAME: 'asa_springlabs_rg'
  SPRING_APPS_SERVICE: springappssvc5e4b10
  AZURE_LOCATION: 'eastus'

  API_GATEWAY: api-gateway
  API_GATEWAY_JAR: spring-petclinic-api-gateway/target/spring-petclinic-api-gateway-2.6.11.jar
 
  AZURE_CRED: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: maven build, clean
        run: |
          mvn -B package -DskipTests -Denv=cloud
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar-files    

      
  deploy:
    runs-on: ubuntu-latest
    needs: build
   
    steps:
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar-files      

      - name: Login via Azure CLI
        uses: azure/login@v1.1
        with:
          creds: ${{ env.AZURE_CRED }}

      - name: deploy to production with artifact, api-gateway
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          action: Deploy
          service-name: ${{ env.SPRING_APPS_SERVICE }}
          app-name: ${{ env.API_GATEWAY }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/${{ env.API_GATEWAY_JAR }}
          jvm-options: -Dspring.profiles.active=mysql

          # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout